authnapp/urls.py
from django.urls import path

import authnapp.views as authnapp

app_name = "authnapp"

urlpatterns = [
    path("login/", authnapp.login, name="login"),
    path("logout/", authnapp.logout, name="logout"),
    path("register/", authnapp.register, name="register"),
    path("edit/", authnapp.edit, name="edit"),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

from .apps import BasketappConfig

app_name = BasketappConfig.name

urlpatterns = [
    path("", basketapp.basket, name="view"),
    path("add/<int:pk>/", basketapp.basket_add, name="add"),
    path("remove/<int:pk>)/", basketapp.basket_remove, name="remove"),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", mainapp.main, name="main"),
    path("products/", include("mainapp.urls", namespace="products")),
    path("contact/", mainapp.contact, name="contact"),
    path("auth/", include("authnapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = "mainapp"

urlpatterns = [
    path("", mainapp.products, name="index"),

    path("category/<int:pk>/", mainapp.products, name="category"),

]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="имя", max_length=64, unique=True)
    description = models.TextField(verbose_name="описание", blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="имя продукта", max_length=128)
    image = models.ImageField(upload_to="products_images", blank=True)
    short_desc = models.CharField(verbose_name="краткое описание продукта", max_length=60, blank=True)
    description = models.TextField(verbose_name="описание продукта", blank=True)
    price = models.DecimalField(verbose_name="цена продукта", max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name="количество на складе", default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

class Contact(models.Model):
    phone = models.CharField(max_length=50, verbose_name="номер телефона")
    email = models.EmailField(max_length=254, verbose_name="электронная почта")
    city = models.CharField(max_length=128, default="Москва", verbose_name="город")
    address = models.CharField(max_length=254, verbose_name="адресс")

    def __str__(self):
        return f"{self.pk} {self.email}"

mainapp/views.py
from django.conf import settings

from django.shortcuts import get_object_or_404, render
from django.utils import timezone

from basketapp.models import Basket

from .models import Contact, Product, ProductCategory



def main(request):
    title = "главная"


    products = Product.objects.all()[:4]

    content = {"title": title, "products": products, "media_url": settings.MEDIA_URL}
    return render(request, "mainapp/index.html", content)


def products(request, pk=None):
    title = "продукты"
    links_menu = ProductCategory.objects.all()

    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
        # or you can use this
        # _basket = request.user.basket.all()
        # print(f'basket / _basket: {len(_basket)} / {len(basket)}')

    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by("price")
            category = {"name": "все"}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by("price")
        content = {
            "title": title,
            "links_menu": links_menu,
            "category": category,
            "products": products,
            "media_url": settings.MEDIA_URL,
            "basket": basket,
        }
        return render(request, "mainapp/products_list.html", content)

    same_products = Product.objects.all()
    content = {
        "title": title,
        "links_menu": links_menu,
        "same_products": same_products,
        "media_url": settings.MEDIA_URL,

        "same_products": same_products,
        "basket": basket,
    }
    if pk:
        print(f"User select category: {pk}")

    return render(request, "mainapp/products.html", content)


def contact(request):
    title = "о нас"
    visit_date = timezone.now()

    locations = Contact.objects.all()
    content = {"title": title, "visit_date": visit_date, "locations": locations}
    return render(request, "mainapp/contact.html", content)

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|capfirst }}
        {% endblock title %}
    </title>

    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock css %}

    {% block js %}
    {% endblock js %}

</head>

<body>
    <div class="container">

        {% block menu %}
        {% endblock menu %}

        <div class="content">
        {% block content %}
        {% endblock content %}
        </div>

    </div>

    {% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
    </div>
    {% endblock %}

</body>

</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block menu %}
<div class="hero">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_menu.html' %}
    </div>
    <h1>наши контакты</h1>
    <p>сегодня: {{ visit_date|date:"l, j F, Y" }}</p>
</div>
{% endblock %}

{% block content %}
<div class="location">
    {% for location in locations %}
    <div class="location-1">
        <i class="fa fa-map-marker fa-5x"></i>
        <h4>{{ location.city }}</h4>
        <div class="contacts">
            <h5>Телефон</h5>
            <p>{{ location.phone }}</p>
        </div>
        <div class="contacts">
            <h5>Email</h5>
            <p>{{ location.email }}</p>
        </div>
        <div class="contacts">
            <h5>Адрес</h5>
            <p>{{ location.address }}</p>
        </div>
    </div>
    {% endfor %}
</div>

<div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block menu %}
<div class="slider">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_menu.html' %}
    </div>
    <div class="text-slider">
        <h3 class="green">тенденции</h3>
        <h3 class="big"> удобные стулья</h3>
        <p>Новый уровень комфорта. Отличные характеристики.</p>
        <a href="#" class="button-order">
            заказать
            <img src="{% static 'img/arrow.png' %}" alt="">
        </a>
    </div>
    <div class="navi">
        <a href="#"></a><a href="#"></a><a href="#"></a>
    </div>
</div>
{% endblock %}


{% block content %}
<div class="featured">
    <div class="featured-menu">
        <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
    </div>
    <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
    <div class="clearfix">
    </div>
    <div class="tab-content">
        {% for product in products %}
        <div class="block">
            <a href="{{ product.image }}"><img src="{{ media_url }}{{ product.image }}" alt="{{ product.short_desc }}">
                <div class="text">
                    <img src="{% static 'img/icon-hover.png' %}" alt="img">
                    <h4>{{ product.name }}</h4>
                    <p>Описание: {{ product.description }} </p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

<div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block menu %}
<div class="hero-white">
	<div class="header clearfix">
		{% include 'mainapp/includes/inc_menu.html' %}
	</div>
</div>
{% endblock %}

{% block content %}
<div class="details">
	<div class="links clearfix">
		{% include 'mainapp/includes/inc_categories_menu.html' %}
	</div>

	<div class="details-products">
		<div class="details-slider">
			<div class="slider-product">
				<img src="{% static 'img/slider1.jpg' %}">
			</div>
			<div class="slider-control">
				<div class="block">
					<a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
						<div class="text"></div>
					</a>
				</div>
			</div>
		</div>

		<div class="description">
			<h3 class="big-bold">Отличный стул</h3>
			<h3 class="red">горячее предложение</h3>
			<p class="price"> 2585.9 <span>руб</span></p>
			<a href="#" class="red-button">
				заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
			</a>
			<div class="description-text">
				<p>Расположитесь комфортно.</p>
				<p>Отличное качество материалов
					позволит вам это.</p>
				<p>Различные цвета</p>
				<p>высочайший уровень
					эргономики и прочность.</p>
			</div>
		</div>
	</div>

	<div class="related">
		<div class="title clearfix">
			<h2>Похожие продукты</h2>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
		</div>
		<div class="related-products clearfix">
			{% for product in same_products %}
			<div class="block">
				<a href="#"><img src="{{ media_url }}{{ product.image }}" alt="{{ product.short_desc }}">
					<div class="text">
						<img src="/static/img/icon-hover.png" alt="img">
						<h3>Категория:{{ product.category.name }}</h3>
						<h4>Название: {{ product.name }}</h4>
						<p>Описание: {{ product.description }} </p>
						<p>Цена: {{ product.price }} </p>
						<p>На складе: {{ product.quantity }} </p>
					</div>
				</a>
			</div>
			{% endfor %}

		</div>
	</div>
</div>

<div class="clr"></div>

{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends "mainapp/products.html" %}
{% load static %}

{% block content %}
<div class="details">
    <div class="links clearfix">
        {% include "mainapp/includes/inc_categories_menu.html" %}
    </div>

    <div class="products_list">
        <div class="title clearfix">
            <h2>Категория: "{{ category.name|title }}"</h2>
        </div>
        <div class="category-products clearfix">
            {% for product in products %}
            <div class="block">
                {% if user.is_authenticated %}
                <a href="{% url 'basket:add' product.pk %}">
                    {% else %}
                    <a href="{% url 'auth:login' %}">
                        {% endif %}
                        <img src="{{ media_url }}{{ product.image }}" alt="{{ product.short_desc }}">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.description }} </p>
                        </div>
                    </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<div class="clr"></div>

{% endblock %}